# Generated by Django 6.0.3 on 2026-03-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('ml_feature_name', models.CharField(blank=True, help_text='Ex: procrastination_score', max_length=100, null=True)),
                ('is_reverse', models.BooleanField(default=False, help_text='Bifează doar dacă scorul e inversat (ex: Reziliență)')),
                ('order', models.IntegerField(default=0)),
                ('is_numeric', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='study_year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Liceu', 'Liceu'), ('Licență', 'Licență'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='employment',
            field=models.CharField(choices=[('Nu', 'Nu'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default='Nu', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='field',
            field=models.CharField(blank=True, choices=[('Real', 'Real / Inginerie / Științe Exacte'), ('Uman', 'Uman / Social / Litere / Psihologie'), ('Medicină', 'Medicină / Sănătate'), ('Economic', 'Economic / Business'), ('Vocațional', 'Vocațional / Arte / Sport')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='financial_stress',
            field=models.IntegerField(blank=True, help_text='1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Feminin', 'Feminin'), ('Masculin', 'Masculin'), ('Nespecificat', 'Nespecificat')], default='Nespecificat', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='study_stage',
            field=models.CharField(blank=True, choices=[('Anul 1', 'Anul 1'), ('Anul 2', 'Anul 2'), ('Anul 3', 'Anul 3'), ('An Terminal', 'An Terminal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institution'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='predicted_cluster',
            field=models.CharField(blank=True, help_text='Clusterul prezis de XGBoost', max_length=50, null=True),
        ),
    ]
