# Generated by Django 6.0.3 on 2026-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_remove_studentprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='sleep_hours',
            field=models.FloatField(blank=True, help_text='Ore somn pe noapte', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='study_hours',
            field=models.FloatField(blank=True, help_text='Ore studiu zilnic', null=True),
        ),
    ]
