# Generated by Django 6.0.3 on 2026-04-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='financial_stress',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='study_hours',
        ),
    ]
