# Generated by Django 6.0.3 on 2026-04-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_studentprofile_financial_stress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='employment',
        ),
    ]
