# Generated by Django 6.0.3 on 2026-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_studentprofile_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='study_stage',
            field=models.CharField(blank=True, choices=[('Anul 1', 'Anul 1'), ('Anul 2', 'Anul 2'), ('Anul 3', 'Anul 3'), ('Anul 4+', 'Anul 4+')], max_length=20, null=True),
        ),
    ]
