# Generated by Django 6.0.3 on 2026-05-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_studentprofile_study_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='employment',
            field=models.CharField(blank=True, choices=[('Nu', 'Nu'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time')], max_length=20, null=True),
        ),
    ]
