# Generated by Django 6.0.3 on 2026-05-07 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentprofile_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='taken_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
