# Generated by Django 6.0.3 on 2026-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_testresult_taken_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilizator cu această adresă de email există deja.'}, max_length=254, unique=True),
        ),
    ]
